print("Hello World")
print("Hello")
print("Hello 'World'")
print('Hello "World"')
print('Hello '+'world')
print("Hello World "*3)
print("H ello"[1])
print('hello world'.capitalize())
print('hello world'.upper())
print('hello world'.__len__())
len('hello world')
print('Hello world'.replace('world'[2], 'programming'))
