puts("Hello World")
puts("Hello")
puts("Hello 'World'")
puts('Hello "World"')
puts('Hello '+'world')
puts("Hello "*3)
puts("H ello"[0])
puts('hello world'.capitalize())
puts('hello world'.upcase())
puts('hello world'.length())
puts('Hello world'.sub('world'[2], 'programming'))
